// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_API.Data;

namespace Projeto_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250506003923_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Projeto_API.models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dataNasc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("foto")
                        .HasColumnType("BLOB");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("professorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("professorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 2023001,
                            dataNasc = "15/03/2002",
                            nome = "João",
                            professorId = 1,
                            sobrenome = "Santos"
                        },
                        new
                        {
                            Id = 2023002,
                            dataNasc = "22/07/2001",
                            nome = "Maria",
                            professorId = 2,
                            sobrenome = "Oliveira"
                        },
                        new
                        {
                            Id = 2023003,
                            dataNasc = "10/11/2000",
                            nome = "Pedro",
                            professorId = 3,
                            sobrenome = "Costa"
                        },
                        new
                        {
                            Id = 2023004,
                            dataNasc = "05/05/2003",
                            nome = "Laura",
                            professorId = 4,
                            sobrenome = "Fernandes"
                        },
                        new
                        {
                            Id = 2023005,
                            dataNasc = "18/09/2002",
                            nome = "Gabriel",
                            professorId = 5,
                            sobrenome = "Martins"
                        },
                        new
                        {
                            Id = 2023006,
                            dataNasc = "30/01/2001",
                            nome = "Beatriz",
                            professorId = 1,
                            sobrenome = "Rocha"
                        },
                        new
                        {
                            Id = 2023007,
                            dataNasc = "12/12/2000",
                            nome = "Rafael",
                            professorId = 2,
                            sobrenome = "Lima"
                        },
                        new
                        {
                            Id = 2023008,
                            dataNasc = "08/08/2003",
                            nome = "Isabela",
                            professorId = 3,
                            sobrenome = "Souza"
                        });
                });

            modelBuilder.Entity("Projeto_API.models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            foto = "/images/dg5dz0zn.png",
                            nome = "Carlos",
                            sobrenome = "Magno"
                        },
                        new
                        {
                            Id = 2,
                            nome = "Mariana",
                            sobrenome = "Silveira"
                        },
                        new
                        {
                            Id = 3,
                            nome = "Roberto",
                            sobrenome = "Fontes"
                        },
                        new
                        {
                            Id = 4,
                            nome = "Ana",
                            sobrenome = "Carolina"
                        },
                        new
                        {
                            Id = 5,
                            nome = "Lucas",
                            sobrenome = "Pereira"
                        });
                });

            modelBuilder.Entity("Projeto_API.models.Aluno", b =>
                {
                    b.HasOne("Projeto_API.models.Professor", "professor")
                        .WithMany("alunos")
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
