// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_API.Data;

namespace Projeto_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250403024641_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Projeto_API.models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dataNasc")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("professorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("professorId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 2023001,
                            dataNasc = "11/09/2001",
                            nome = "Aluno",
                            professorId = 1,
                            sobrenome = "A"
                        },
                        new
                        {
                            Id = 2023002,
                            dataNasc = "11/09/2001",
                            nome = "Aluno",
                            professorId = 2,
                            sobrenome = "B"
                        },
                        new
                        {
                            Id = 2023003,
                            dataNasc = "11/09/2001",
                            nome = "Aluno",
                            professorId = 3,
                            sobrenome = "C"
                        });
                });

            modelBuilder.Entity("Projeto_API.models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            nome = "Pericles",
                            sobrenome = "Pericles"
                        },
                        new
                        {
                            Id = 2,
                            nome = "The",
                            sobrenome = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            nome = "Pspspsps",
                            sobrenome = "Da Silva"
                        });
                });

            modelBuilder.Entity("Projeto_API.models.Aluno", b =>
                {
                    b.HasOne("Projeto_API.models.Professor", "professor")
                        .WithMany("alunos")
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
