// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_API.Data;

namespace Projeto_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250606200255_AdicionarUsuario")]
    partial class AdicionarUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Projeto_API.models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("dataNasc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("foto")
                        .HasColumnType("BLOB");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("professorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("cpf")
                        .IsUnique();

                    b.HasIndex("professorId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Projeto_API.models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("cpf")
                        .IsUnique();

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Projeto_API.models.Usuario", b =>
                {
                    b.Property<string>("nomeUsuario")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("senha")
                        .HasColumnType("TEXT");

                    b.HasKey("nomeUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Projeto_API.models.Aluno", b =>
                {
                    b.HasOne("Projeto_API.models.Professor", "professor")
                        .WithMany("alunos")
                        .HasForeignKey("professorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
